### ISSUE TITLE
Please create a script+hook for updating your fork

### ISSUE THREAD

**Issue by Liamsi** [aminb/rust-for-c#5]
As you might have noticed, your gitbook ranks higher in search results as the original github repo. On the hand this is nice, as it is more comfy to read (searchable etc) on the other hand the information is quite outdated (last update 6 months ago).

Please: 
1) [keep your fork synced](https://help.github.com/articles/syncing-a-fork/) manually (or automatically check for updates using a simple script)  
2) use [webhooks to keep your gitbook synced](http://help.gitbook.com/github/index.html) with your fork

You could notice @nrc. There is an open issue on this topic: https://github.com/nrc/r4cppp/issues/6

Thanks for your efforts :+1:

**Comment by Liamsi** [comment]
OK, I just recognized, this repo isn't even a fork. Maybe it is good idea to fork the original repo (and follow the above proposals)

**Comment by aminb** [comment]
@Liamsi Yeah this is not a fork, I created this repo (and the gitbook) ~1 year ago, and at that time I did offer to transfer the ownership of the repo and the gitbook to @nrc, but never heard from him.

I see that @ncr has created a repo ([nrc/r4cppp](https://github.com/nrc/r4cppp/)) for the book, which is nice. However, I don't think I'd be forking it, since this repo has already been set up with gitbook; so I'd have to delete this, fork the original repo, make it into a structure acceptable by gitbook, and unfortunately I don't have the time for all of that stuff. Also, I'm pretty sure I'll mess up the gitbook and the stats somewhere along that path.

I'll update this repo with the new content, and the gitbook will automatically be updated, since I've already set up a webhook.

**Comment by Liamsi** [comment]
OK, either way, I think updating your book would be nice, as there is enough outdated information about Rust floating around the web.  
Thank's for your prompt reply  :-)

**Comment by aminb** [comment]
> OK, either way, I think updating your book would be nice, as there is enough outdated information about Rust floating around the web.

@Liamsi I completely agree, I'll update the repo sometime this weekend :)

> Thank's for your prompt reply :-)

You're very welcome, and thank *you* for bringing this up, as I didn't know @ncr had created a repo and had posted 2 new \*chapters\*.

**Comment by nrc** [comment]
Oh hai! @aminb sorry I never got back to you last year, I think I just saw one thing fly by on Twitter and then forgot to act on it. Thanks for maintaining this and in advance for updating!

@Liamsi thanks for finding this and cc'ing me!

**Comment by aminb** [comment]
@nrc Hi Nick, yeah that was me on Twitter haha. It's fine though no worries. Expect an email from me this week about your book and this repository.

@Liamsi I've updated the gitbook and I'm closing the issue, thanks for bringing this up :)

**Comment by ibraheemdev** [comment]
This repo is now far behind the original. Can they be merged if this is no longer being maintained?
